updated links in serverless articles
prisma/dataguide pull request #285
Opened 2022-03-30 16:18 UTC by etelsv

2022-03-31 12:23 UTC, alex-emerich requested changes

2022-03-31 12:23 UTC, alex-emerich commented on content/11-serverless/02-serverless-comparison.mdx
> +Learn more about how [Prisma and Planetscale work together](https://www.prisma.io/planetscale.
```suggestion
Learn more about how [Prisma and Planetscale work together](https://www.prisma.io/planetscale).
```

2022-03-31 12:25 UTC, imchairmanm commented on content/11-serverless/02-serverless-comparison.mdx
> +<PrismaOutlinks>
I think you might need another blank link beneath this one.  We had some rendering issues without that in the past.

2022-03-31 12:26 UTC, imchairmanm commented on content/11-serverless/02-serverless-comparison.mdx
> +Cloudflare Workers is a very attractive solution for many projects due to its low latency delivery and high performance execution environment.  The platform is designed specifically to allow for quic
```suggestion
Cloudflare Workers is a very attractive solution for many projects due to its low latency delivery and high performance execution environment.  The platform is designed specifically to allow for quick execution of small, focused functions at the [edge](/serverless/serverless-glossary#edge-computing).
```

2022-03-31 12:27 UTC, imchairmanm commented on content/11-serverless/02-serverless-comparison.mdx
> +Learn more about how [Prisma and Planetscale work together](https://www.prisma.io/planetscale.
```suggestion
Learn more about how [Prisma and Planetscale work together](https://www.prisma.io/planetscale).
```

2022-03-31 12:28 UTC, imchairmanm commented on content/11-serverless/03-serverless-challenges.mdx
> +One of the most commonly discussed challenges when working with serverless is called the *[cold start](/serverless/serverless-glossary#cold-start)* problem.  While the goal with serverless is allow f
```suggestion
One of the most commonly discussed challenges when working with serverless is called the [*cold start*](/serverless/serverless-glossary#cold-start) problem.  While the goal with serverless is allow functions to immediately be executed on demand, there are some scenarios that may result in predictable delays.
```

2022-03-31 12:28 UTC, imchairmanm commented on content/11-serverless/02-serverless-comparison.mdx
> +</PrismaOutlinks
```suggestion
</PrismaOutlinks>
```

2022-04-01 16:22 UTC, imchairmanm commented on content/11-serverless/02-serverless-comparison.mdx
> +<PrismaOutlinks>
```suggestion
<PrismaOutlinks>

```

2022-04-01 16:27 UTC, imchairmanm approved these changes

2022-04-01 16:33 UTC, alex-emerich approved these changes

2022-04-05 16:36 UTC, merged